//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Iteris;

namespace PortalDeFluxos.Core.BLL.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class AnexoFacilIntegracao : EntidadeDB, IEntidadeDBCore
    {
    	
        public int ID { get; set; }
    	
        public int CodigoTipoProposta { get; set; }
    	
        public int ValorProposta { get; set; }
    	
        public int CodigoIntegracao { get; set; }
    	
        public string DescricaoLink { get; set; }
    }
}
