//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Iteris;

namespace PortalDeFluxos.Core.BLL.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class AnexoFacil : EntidadeDB, IEntidadeDBCore
    {
    	
        public int ID { get; set; }
    	
        public System.Guid CodigoLista { get; set; }
    	
        public int CodigoItem { get; set; }
    	
        public int CodigoAnexoFacil { get; set; }
    	
        public Nullable<int> CodigoIntegracao { get; set; }
    }
}
