//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Iteris;

namespace PortalDeFluxos.Core.BLL.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class CEGR_Cidade : EntidadeDB, IEntidadeDBCore
    {
    	
        public int IdCEGR_Cidade { get; set; }
    	
        public int IdCEGR { get; set; }
    	
        public int IdCidade { get; set; }
    
        public virtual CEGR CEGR { get; set; }
        public virtual Cidade Cidade { get; set; }
    }
}
