
//------------------------------------------------------------------------------
// <auto-generated>
// Código Gerado via T4
//
// Não alterar o código - As informações serão perdidadas.
// </auto-generated>
//------------------------------------------------------------------------------
using PortalDeFluxos.Core.BLL.Atributos;
using System;
using System.Collections.Generic;
using Iteris;
using PortalDeFluxos.Core.BLL.Modelo;


namespace PortalDeFluxos.INFO_PROPOSTA.BLL.Modelo
{
		
	[InternalName("InformacoesDaProposta")]
	public class ListaSP_InformacoesDaProposta : EntidadePropostaSP
	{
		[InternalName("CNPJ",FieldType.ReiniciarWF)]
		public String CNPJ { get; set; }

		[InternalName("Endereco",FieldType.ReiniciarWF)]
		public String Endereco { get; set; }

		[InternalName("Bairro",FieldType.ReiniciarWF)]
		public String Bairro { get; set; }

		[InternalName("Cidade",FieldType.ReiniciarWF)]
		public String Cidade { get; set; }

		[InternalName("CEP",FieldType.ReiniciarWF)]
		public String CEP { get; set; }

		[InternalName("UF",FieldType.ReiniciarWF)]
		public String UF { get; set; }

		[InternalName("Mercado",FieldType.ReiniciarWF)]
		public String Mercado { get; set; }

	}
		
}